
# Database
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/tabdyl
        username: admin
        password: tabdyl2020
    jpa:
        hibernate:    
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
